# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - pip install -U pip
  - pip install -U setuptools
  - pip install coverage
  - pip install six
  - pip install nose
script:
  - nosetests
